version: '2'
services:
  podium-elasticsearch-1:
    build: elasticsearch/
    container_name: podium-elasticsearch-1
    environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
        memlock:
            soft: -1
            hard: -1
    mem_limit: 1g
    volumes:
        - esdata1:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
        - 9300:9300
    networks:
        - pdmnet

  podium-logstash:
    build: logstash/
    ports:
        - 5000:5000
        - 9600:9600
    depends_on:
        - podium-elasticsearch-1
    networks:
        - pdmnet

  podium-kibana:
    build: kibana/
    container_name: podium-kibana
    environment:
        - ELASTICSEARCH_URL=http://podium-elasticsearch-1:9200
    ports:
        - 5601:5601
    depends_on:
        - podium-elasticsearch-1
    networks:
        - pdmnet

  podium-import-dashboards:
    build: import-dashboards/
    environment:
        - ELASTICSEARCH_URL=http://podium-elasticsearch-1:9200
    depends_on:
        - podium-elasticsearch-1
    networks:
        - pdmnet

  podium-alerter:
    build: alerter/
    # Uncomment this section to enable alerting
    volumes:
        - ./alerter/config.yaml:/opt/elastalert/config.yaml
        - ./alerts/rules/:/opt/elastalert/rules
    depends_on:
        - podium-elasticsearch-1
    networks:
        - pdmnet

  podium-curator:
    build: curator/
    environment:
        - ES_HOST=podium-elasticsearch-1
        - UNIT_COUNT=7
        - UNIT=days
    depends_on:
        - podium-elasticsearch-1
    networks:
        - pdmnet

  podium-zipkin:
    build: zipkin/
    environment:
        - ES_HOSTS=http://podium-elasticsearch-1:9200
        - ZIPKIN_UI_LOGS_URL=http://podium-kibana:5601/app/kibana#/dashboard/logs-dashboard?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-1h,mode:quick,to:now))&_a=(filters:!(),options:(darkTheme:!f),panels:!((col:1,id:logs-levels,panelIndex:2,row:1,size_x:6,size_y:3,type:visualization),(col:7,columns:!(stack_trace),id:Stacktraces,panelIndex:7,row:1,size_x:4,size_y:3,sort:!('@timestamp',desc),type:search),(col:11,id:Log-forwarding-instructions,panelIndex:8,row:1,size_x:2,size_y:3,type:visualization),(col:1,columns:!(app_name,message),id:All-logs,panelIndex:9,row:4,size_x:12,size_y:7,sort:!('@timestamp',asc),type:search)),query:(query_string:(analyze_wildcard:!t,query:'{traceId}')),title:logs-dashboard,uiState:())
    ports:
        - 9411:9411
    depends_on:
        - podium-elasticsearch-1
    networks:
        - pdmnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  pdmnet:
