analysis:
    filter:
        edge_autocomplete_filter:
            type: edge_ngram
            min_gram: 1
            max_gram: 15
    analyzer:
        autocomplete:
            type: custom
            tokenizer: edge_ngram_tokenizer
            filter: [
                "lowercase",
                "edge_autocomplete_filter"
            ]
    tokenizer:
        edge_ngram_tokenizer:
            type: edgeNGram
            min_gram: 1
            max_gram: 15
            token_chars: ["letter", "digit"]
