version: '2'
services:
    podium-elasticsearch:
        container_name: podium-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.15
        # volumes:
        #     - ~/volumes/podium/podiumGateway/elasticsearch/:/usr/share/elasticsearch/data/
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
            - 9300:9300
