@startuml
node "Registry" {
  [Registry API]
  [Admin Webapp] --> [Registry API]
}

node "UAA" {
  [User Auth API] --> [Registry API]
}

node "Gateway" {
  [Gateway API] --> [Registry API]
  [Podium Webapp] --> [Gateway API]
}

cloud {
  [Github Config]
  [Registry API] --> [Github Config] : (if Cloud Config enabled)
}

rectangle Common [
  podium-common
  * Shared DTOs
  * Request type and status enums
  * Event definitions
  * Exception classes
  * etc
]

[Gateway API] ..> Common
[User Auth API] ..> Common


database "PostgreSQL" {
  frame "Auth DB" as AuthDB {
  }
  frame "Request DB" as RequestDB {
  }
}

rectangle "Auth ES Index" as AuthES
AuthES -[hidden]-> AuthDB
rectangle "Request ES Index" as RequestES
RequestES -[hidden]-> RequestDB

@enduml
