/*
 * Copyright (c) 2017  The Hyve and respective contributors.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * See the file LICENSE in the root of this repository.
 */

package nl.thehyve.podium.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AccessLevel;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import nl.thehyve.podium.common.IdentifiableOrganisation;
import nl.thehyve.podium.common.enumeration.RequestType;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;

/**
 * An Organisation.
 */
@Entity
@Table(name = "organisation")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Data
public class Organisation implements Serializable, IdentifiableOrganisation {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "organisation_seq_gen")
    @GenericGenerator(
        name = "organisation_seq_gen",
        strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator",
        parameters = {
            @Parameter(name = "sequence_name", value = "organisation_seq"),
            @Parameter(name = "initial_value", value = "1000"),
            @Parameter(name = "increment_size", value = "50")
        }
    )
    private Long id;

    @Column(unique = true, nullable = false)
    @Setter(AccessLevel.NONE)
    private UUID uuid;

    @NotNull
    @Column(name = "name", nullable = false)
    private String name;

    @NotNull
    @Size(max = 50)
    @Column(name = "short_name", length = 50, nullable = false)
    private String shortName;

    @JsonIgnore
    @Column(name = "deleted", nullable = false)
    @Getter(AccessLevel.NONE)
    private boolean deleted;

    @Column(name = "activated", nullable = false)
    @Getter(AccessLevel.NONE)
    private boolean activated;

    @JsonIgnore
    @OneToMany(mappedBy = "organisation")
    @Cascade(CascadeType.ALL)
    private Set<Role> roles;

    @Fetch(FetchMode.JOIN)
    @ElementCollection(targetClass = RequestType.class, fetch = FetchType.EAGER)
    @Enumerated(EnumType.STRING)
    @CollectionTable(
        name="organisation_request_types",
        joinColumns=@JoinColumn(name="organisation_id")
    )
    @Column(name = "request_type")
    private Set<RequestType> requestTypes;

    public UUID getOrganisationUuid() {
        return getUuid();
    }

    /**
     * UUID is generated by the DBMS and cannot be overridden.
     * @param uuid This will be passed by syntax is satisfies for Hibernate and used mappers.
     */
    public void setUuid(UUID uuid) {
        // pass
    }

    @PrePersist
    public void generateUuid() {
        if (this.uuid == null) {
            this.uuid = UUID.randomUUID();
        }
    }

    public Organisation name(String name) {
        this.name = name;
        return this;
    }

    public Organisation shortName(String shortName) {
        this.shortName = shortName;
        return this;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public boolean isActivated() {
        return activated;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Organisation organisation = (Organisation) o;
        if (organisation.id == null || id == null) {
            return false;
        }
        return Objects.equals(id, organisation.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "Organisation{" +
            "id=" + id +
            ", uuid=" + uuid +
            ", name='" + name + '\'' +
            ", shortName='" + shortName + '\'' +
            ", deleted=" + deleted +
            ", activated=" + activated +
            ", requestTypes=" + requestTypes +
            '}';
    }
}
